---
title: "Testimonies and Supervisions"
  # template: trestles
# listing:
#   contents: publications
#   sort: "date desc"
#   type: default
#   categories: false
#   sort-ui: false
#   filter-ui: false
# page-layout: full
# title-block-banner: true
---

**SUPERVISORY** **MASTERS STUDENTS RESEARCH**

1.  Effect of Forensic Accounting Techniques on Fraud Prevention in Deposit-Taking Savings and Credit Cooperative Organizations in Nairobi, Kenya; Mokaya Gladys Kerubo ondari; Reg No: 17/00675

2.  Effect of Audit Committee Characteristics on Financial Performance of Savings and Credit Cooperative Societies in Kenya; Chebor K. Christopher; Adm No 19/01420

3.  Effect of Risk Management Practices on Financial Performance of Development Financial institutions in Kenya; Chacha Mwita Marwa; Reg: 19/07031; Kca University A Master of Science Degree in Development Finance

4.  Effect of Microfinance Services on ohe Growth of Women-Owned Enterprises in Kiambu County; by Esther N. Kinga; Master of Science (Finance and Accounting Option) School of Business Kca), University

5.  Effect of Forensic Accounting on Financial Performance of Nairobi Securities Exchange Listed insurance Firms Kenya; Kobi Matib; Master of Science in Commerce; Finance and Accounting; Kca University; 20235.

6.  Effect of External Auditing Practices on Financial Accountability in the County Government of Kitui Kenya; onesmus Kitonyo; No: 18/02763; Master of Science in Commerce (Finance and Accounting; Kca University

7.  Effect of Microfinance Services on the Growth of Women-Owned Enterprises in Kiambu County; Esther N. Kinga; No: 22/00694; Master of Science (Finance and

8.  Accounting Optionkca, University; July, 2023

**EXAMINER- MASTERS PROPOSAL**

1.  “Impact of Basel Accord on Risk Management by Listed Commercial Banks in Kenya”; Reg No: Adm: 13/00809; Omuse Duncan

2.  Effect of Financial Literacy on Rental Tax Compliance Among Landlords in Machakos County Kenya; Elias Aguta Mochiemo; Reg. No. Kca19/00892; Master of Finance and Accounting; Kca University; 2023

3.  Effect of Financial Risks on Financial Performance of Deposit-Taking Savings and Credit Cooperative Societies in Kiambu County, Kenya; Geoffrey Mweu Kithuka; Admn No: 10/01614; Master of Finance and Accounting; Kca University; 2023

4.  “Development Finance and Economic Development in Kenya” Grace Kanini Mbuta

5.  “Impact of Basel Accord on Risk Management by Listed Commercial Banks in Kenya” Omuse Duncan; 13/00809;

6.  “Effect of Forensic Accounting on Financial Performance of County Governments of Kenya” Timothy Omonge; 22/02631

7.  “Effect of Bank Characteristics on interest Rate Spread of Commercial Banks in Kenya; Nelly Akoth Mitoko

8.  the Effects of Financing Strategies on the Growth of the Real Estate Sector in Nairobi Metrpolitan in Kenya; Silas Wanjala Osundwa; 12/02681;; Masters ; Kca University; October, 2023

**SUPERVISORY/EXAMINER DEGREE STUDENTS RESEARCH**

1.  The Impact of Accounting information Systems Usage on Financial Performance of Manufacturing Companies in Nairobi; Mutisya Esther Kalekye; 19/02222; Bachelot of Commerce Degree Kca Universitty; 2023

2.  The Effect of Training and Development on Employee Performance in Manufacturing Companies in Kenya; A Case Study of Epza Kenya; Priscah Jane Kasina; 21/00368; Bachelor of Commerce (Bcom) Human Resource Option in Kca University; May 2023

3.  Factors Affecting the integrity of Financial Statements in the Public Sector and Performance; (A Case Study of Public institutions in Kiambu County); Njuguna Ruth Magiri; Reg No. 21/01233; Bachelors of Commerce Degree Programme; Kca University December 2022

4.  Effect of Planning on Purchasing and Performance in Manufacturing Companies in Kenya: A Case Study of Athi-River Limited Company; Nzioka Gerald Manasseh;

5.  19/03192; Bachelor of Procurement and Logistics in Kca University; November 2022

6.  The Effect of Mergers and Acquisitions on the Financial Performance of Commercial Banks; Kamau Joseph Wanyoike; Kcau/11/00947; Bachelor of Commerce Degree; April 2023

**MANUALS AND BOOKS FOR PUBLICATIONS**

1.  A New Approach to Accountancy; A Wonderful Companion; Volume I

2.  A New Approach to Accountancy Vol 1; Special Accounts

3.  A Teacher’s Wonderful Companion Vol. II; Company Accounts

4.  Role of internal Control Systems on Firm Performance of Companies Quoted in the Nairobi Securities Exchange

5.  forensic accounting, financial reporting quality; accountability practices and fraud prevention of devolved units Kenya.
